# Generated by Django 3.1 on 2020-08-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletplatform',
            name='type',
            field=models.CharField(choices=[('BANCO', 'BANCO'), ('E-WALLET', 'E-WALLET'), ('CRYPTOCURRENCY', 'CRYPTOCURRENCY')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
