# Generated by Django 3.1 on 2020-08-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0004_auto_20200816_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplatform',
            name='account',
            field=models.CharField(default='--', max_length=99),
        ),
    ]
